apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  app-name: Cintra
  app-version: 1.0.0
  app-description: Pipeline tunneling with AI
  app-owner: CoFex

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app
spec:
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
      - name: config-app
        image: busybox
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "env && sleep 3600"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: app-properties # name of config map
                key: app-name
          - name: APP_VERSION
            valueFrom:
              configMapKeyRef:
                name: app-properties # name of config map
                key: app-version
